title: Sleepy Pinks
url: "https://sleepypinks.github.io"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/sleepypinks"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Home"
   link: ""
# - name: "Projects"
#  link: "https://sleepypinks.github.io/#Projects"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Google Scholar"
   link: "https://scholar.google.com/citations?user=o8oJ6s4AAAAJ&hl=en"
 
