title: Sleepy Pinks
url: "https://sleepypinks.github.io"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/sleepypinks"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Home"
   link: "https://sleepypinks.github.io/"
 - name: "Projects"
  link: "projects"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
 
