title: Sleepy Pinks
url: "https://sleepypinks.github.io"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/sleepypinks"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 #- name: "About"
 #  link: "/researcher/"
 #- name: "Resume"
 #  link: "resume.pdf"
 - name: "Personas"
   link: "personas"
 - name: "Responsive Redesign"
   link: "redesign"
 - name: "Koko"
   link: "koko"
